name: AOJI PR Target

on: 
    pull_request_target:
        branches:
            - main
        types: [opened, labeled]

jobs:
    aoji:
        if: | # is a fork
            github.event.pull_request.head.repo.full_name != github.repository &&
            contains(github.event.pull_request.labels.*.name, 'aoji-safe')
        name: Run AOJI
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ['3.10']
        
        steps:
          - uses: actions/checkout@v2
            with:
                ref: ${{ github.event.pull_request.head.sha }}
                fetch-depth: 3
                
          - name: Run AOJI
            run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                ./.github/aoji.sh ${{ secrets.AOJ_ID }} ${{ secrets.AOJ_PASSWD }} ${{ github.event.pull_request.head.sha }}

          - name: Upload AOJI Report
            uses: actions/upload-artifact@v2
            with:
                name: aoji-report
                path: .github/aoji_report.md
                if-no-files-found: error

          - name: Check Judge Failure
            id: check_aoji_fail
            uses: andstor/file-existence-action@v1
            with:
                files: ".github/fail.aoji"

          - name: Upload AOJI Fail Report
            if: steps.check_aoji_fail.outputs.files_exists == 'true'
            uses: actions/upload-artifact@v2
            with:
                name: aoji-fail-report
                path: .github/fail.aoji

          - uses: actions/checkout@v2

          - name: Download AOJI Report
            uses: actions/download-artifact@v2
            with:
                name: aoji-report
                path: .github

          - name: Download AOJI Fail Report
            if: steps.check_aoji_fail.outputs.files_exists == 'true'
            uses: actions/download-artifact@v2
            with:
                name: aoji-fail-report
                path: .github

          - name: Comment Report
            uses: actions/setup-ruby@v1
            with:
                ruby-version: '2.7'
          - run: |
                gem install octokit
                ruby ./.github/comment-pr.rb ${{ secrets.GITHUB_TOKEN }} ${{ github.event.pull_request.number }} ".github/aoji_report.md"

          - name: Raise CI Fail
            if: steps.check_aoji_fail.outputs.files_exists == 'true'
            run: exit 1
            